### PR TITLE
(feat) add more categories for post

### LINKED ISSUE #45: Add mentorship request on categories
The purpose of this will be to allow users to request for mentorship on the platform...

And also sort stories by date, and later we can sort by likes

Let self-assigned this to me @espoirMur !

### PR DESCRIPTION
**Pull request by espoirMur**
#### What does this PR do?
Add 2 more categories on a post creation

#### Description of Task to be completed?

- Refractor the code of adding categories, create 2 categories

#### How should this be manually tested?

Open the browser and confirm that you can see  2 categories which are mentorship requests or collaborations.

Try to create a post and verify if it will work with the new categories created.

#### Screenshots (if appropriate)

Screen Shot 2020-05-10 at 20 19 52

#### Questions:
- what do you guys think about this?

Fix #45

### CODE REVIEW

**Comment by oesukam** [comment]
@espoirMur Can you add the screenshot?

**Comment by espoirMur** [comment]
> @espoirMur Can you add the screenshot?

Done @oesukam

**Review by oesukam — APPROVED** [review]
LGTM
@espoirMur are we already allowing those new categories in the backend or we have to add them?

**Comment by espoirMur** [comment]
> LGTM
> @espoirMur are we already allowing those new categories in the backend or we have to add them?

I checked the backend there is no issue with those new categories

**Pull request merged**
