### PR TITLE
Fix: update like and comment count on single post

### PR DESCRIPTION
**Pull request by Karlmusingo**
#### What does this PR do?
Update the likeCount and Comment count on the single post page.
#### Description of Task to be completed?
- add comments on the PostCard component from redux.
- add the method componentWillUpdate in the Like component to update state (highlight) when the props change on the PostCard component.
- remove the comments count and likes count on the PostComments component
#### How should this be manually tested?
Fetch and clone the branch git fetch origin fix-like-and-comment-count-single-post && git checkout fix-like-and-comment-count-single-post
Start the server, click on a post and then like and post a comment.
#### Screenshots (if appropriate)
image

#### Questions:
N/A

### CODE REVIEW

**Comment by Karlmusingo** [comment]
[Fix the like and comment count while viewing a single post](https://trello.com/c/tawmnzub/82-fix-the-like-and-comment-count-while-viewing-a-single-post)

**Comment by Karlmusingo** [comment]
[Update the count of comments](https://trello.com/c/QaiL6fyC/85-update-the-count-of-comments)

**Comment by gracelungu** [comment]
@Karlmusingo Remove the second `like and comment` found on the same page

**Comment by Karlmusingo** [comment]
@gracelungu, done !

**Pull request merged**
