### PR TITLE
Complete the display of the profile

### PR DESCRIPTION
**Pull request by nkpremices**
#### What does this PR do?
Adds the complete display of the profile page and improve the layout of the 404 page 

#### Description of Task to be completed?
* Add the `links` part and the `Following` part on the profile page
* Design the 404 page 

#### How should this be manually tested?
After being logged into the platform, head over to the profile page and notice the difference. Add some whatever string to the url and notice the new 404 page

### CODE REVIEW

**Comment by oesukam** [comment]
@nkpremices What about editing the profile?

**Comment by gracelungu** [comment]
I find the logo and the title too big, can you reduce that to a smaller size? @nkpremices

**Comment by oesukam** [comment]
@nkpremices When hovering the edit icon, the curso should change to show that it's clickable

**Comment by gracelungu** [comment]
@nkpremices I do find the font-size too big on the profile page too, can you reduce the font-size of the different texts?

**Comment by nkpremices** [comment]
> @nkpremices When hovering the edit icon, the curso should change to show that it's clickable

Noted @oesukam. I'm Working on it already

**Review by oesukam — APPROVED** [review]

**Pull request merged**
